server:
  port: 8081
spring:
#  jackson:
#    serialization:
#      write-dates-as-timestamps: false
  application:
    name: auction
  datasource:
    url: jdbc:h2:mem:test
    username: sb
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false