#server:
#  port: 8081
#spring:
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#  application:
#    name: auction
#  datasource:
#    url: jdbc:h2:mem:test
#    username: sb
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    show-sql: false
server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:8091/postgres
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
